spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql

server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8083
  servlet:
    context-path: /

